---2017-6-6 13:36:44【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-6 13:36:47【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-6 13:36:47【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-6 13:36:47【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-6 13:36:47【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-6 13:36:47【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-6 13:36:47【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-6 13:36:47【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-6 13:36:47【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-6 13:36:47【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-6 13:36:47【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-6 13:36:47【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-6 13:36:47【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-6 13:36:47【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-6 13:36:47【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-6 13:36:47【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-6 13:36:47【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-6 13:36:47【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-6 13:36:47【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-6 13:36:47【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\_pg@4.5.6@pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
